export const DASHBOARD_LOAD_ROOM_BEGIN = 'DASHBOARD_LOAD_ROOM_BEGIN';
export const DASHBOARD_LOAD_ROOM_SUCCESS = 'DASHBOARD_LOAD_ROOM_SUCCESS';
export const DASHBOARD_LOAD_ROOM_FAILURE = 'DASHBOARD_LOAD_ROOM_FAILURE';
export const DASHBOARD_LOAD_ROOM_DISMISS_ERROR = 'DASHBOARD_LOAD_ROOM_DISMISS_ERROR';
